# Generated by Django 3.1.1 on 2020-09-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200929_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='D:\\djngoPracticeGit\\django-practices\\blogApp\\media'),
        ),
    ]
